### ISSUE TITLE
Cant open the menus..

### ISSUE THREAD

**Issue by Vitze** [FAXES/hrc-resource#3]
When i type /cmds all it does is play a sound even with default no edited images.

**Comment by lze3** [comment]
Are you receiving an error in your F8 console?

**Comment by codibez** [comment]
I also have this issue, there are 0 errors in my **F8 Console**.

**Comment by sambeano7** [comment]
I also need help. Same issue.

**Comment by simpleC0de** [comment]
no solution?

**Comment by Foookey** [comment]
'ui/index.html',
  'ui/style.css',
  'ui/img/bg-img.png',
  'ui/img/bg-img2.png',
  'ui/img/bg-img3.png',
  'ui/img/bg-img4.png',
  'ui/action.ogg',
  'ui/script.js'
thats the problem you gotta change the bg-img names to the actual names for example   'ui/img/bg-img4.png', to   'ui/img/help.png',
